#!/usr/bin/env bash
# A Bash script that runs the whoami command on the the first arg passed
# to it. Here am assumming the first command passed to the script is a user
# registerred on the system.
sudo -u "$1" whoami
